### ISSUE TITLE
Perform second round of backpopulation using updated CCKP database

### ISSUE THREAD

**Issue by Bankso** [mc2-center/mc2-center-dcc#58]
Since the CCKP staging union tables were qc'd and harmonized during our database update work, we should take the current database and re-backpopulate, to ensure parity between displayed and stored metadata at all database levels. 

Process:
Download CCKP database tables as CSV --> extract text from CSV using regex --> map all metadata onto current template --> apply processing, validation, upload pipeline --> done!

**Comment by aclayton555** [comment]
Not pressing, but consider picking this up late 24-5 sprint. Complements current upload process. These are mostly quality of life improvements.

**Comment by aclayton555** [comment]
Will be making some updates to QC checks on database to reduce scope on only newer entries rather than the WHOLE database, which takes a lot of time.

**Comment by Bankso** [comment]
Updated union_qc script is here: https://github.com/mc2-center/mc2-center-dcc/tree/union-qc-update-issue-58

Updates introduce steps to 1) pull the latest CCKP database CSV, 2) compare select fields between the database and new CSVs, 3) produce a CSV of new/"updated" entries, 4) validate new/"updated" entries 

During testing, I was able to reduce validation of the publications union table to a few minutes after implementing these changes.

Similar to the previous workflow, the validation report can be used to check for issues in the new/"updated" entries. After making changes to the erroneous entries in the merged manifest, this will represent the new CCKP database CSV. I recommend that the merged + corrected manifest be compared to the CCKP database, just to be safe, before uploading to CCKP - Admin.

I'll also note that "updated" is used loosely here, since the script is really just checking if the fields match up perfectly. In some cases, subsequent inspection showed that many "updated" entries were identical to existing entries - my guess is that the differences arise from character encoding similar issues.

With this updated script in-hand, I will proceed with the second round of backpopulation

**Comment by Bankso** [comment]
Backpopulation has been completed for:

- [x] Publications
- [x] Datasets
- [x] Tools
- [x] Educational Resources

**Comment by Bankso** [comment]
Summary of work under this ticket:

- updated union_qc.py to identify new and updated entries in the resource UNION tables, by comparing to the most recent version of the database CSV
- updated schema_update.py to modify a broader set of columns in grant Synapse project tables and added more attribute-specific column casting
- collated current database and UNION tables, then resolved errors in PublicationView, DatasetView, and ToolView metadata (backpopulation)
- validated all "updated" UNION table metadata following backpopulation
