### ISSUE TITLE
Create a system that generate database contribution reports

### ISSUE THREAD

**Issue by Bankso** [mc2-center/mc2-center-dcc#59]
I imagine this is related to Synapse monitoring (noted here: https://github.com/mc2-center/data-models/issues/40), but for metrics on community storage and curation, I was thinking the following approach could be applied via code:

pull synIds for all users that have contributed to files or tables in MC2 projects (in scope of CCKP database all files) --> separate out MC2 admin + previous contributors from Sage from community members --> generate report to store in CCKP - Admin project

Report could include:
- total number of entities modified by MC2 vs community
- number of files uploaded by MC2 vs community
- number of metadata manifests uploaded by MC2 vs community, separated by data type
- relative percent contribution by MC2 vs community
- relative contribution from each consortium
- relative contribution using a rolling window (all time, past year, past six months, past month)

**Comment by Bankso** [comment]
I think this can be built on the system @aditigopalan is putting together (#63 and #60)

**Comment by aclayton555** [comment]
Will continue into 24-6 sprint

**Comment by aclayton555** [comment]
previously marked this as done but neglected to close the issue. closing now.
