### ISSUE TITLE
Implement a validation script to check CCKP uploads

### ISSUE THREAD

**Issue by aditigopalan** [mc2-center/mc2-center-dcc#63]
- [x] Implement a script to check if manifests have been uploaded correctly to their target folders in synapse.
- [x] Create a folder houses records from each monthly curation cycle, indicating the upload timestamp to Synapse for each manifest entry, alongside the corresponding folder targetID.

Note: This script is house in the mc2-center-dcc repo

**Comment by aditigopalan** [comment]
In progress, see #60

**Comment by aclayton555** [comment]
Will continue into 24-5 sprint

**Comment by aclayton555** [comment]
Done, just needs to be pushed to prod
