### ISSUE TITLE
Code review for automated curation workflow

### ISSUE THREAD

**Issue by aditigopalan** [mc2-center/mc2-center-dcc#64]
The [current curation workflow](https://github.com/mc2-center/mc2-center-dcc/tree/main/annotations) is operational, but there is an opportunity to assess whether the code could be enhanced to align with standard engineering practices. Additionally, it would be beneficial to explore potential improvements in the workflow itself.

**Comment by aditigopalan** [comment]
@vpchung I would love to get your review on the current curation workflow and I'm curious about your thoughts on potential improvements. This is however not a high priority item since the workflow is functional

**Comment by vpchung** [comment]
Awesome - I'll take a look later today!

**Comment by aclayton555** [comment]
24-9: part of Aditya onboarding will be to run through scripts. Expect this to close in one or two more sprints.

**Comment by aclayton555** [comment]
24-10: Still pending a complete run through of the process, and will then provide feedback.

**Comment by aditya-nath-sage** [comment]
Have been using these scripts during this sprint cycle, feel more confident with the scripts, think we can close this out!
