### ISSUE TITLE
Incorporate DatasetView_id generating script into curation workflow

### ISSUE THREAD

**Issue by aditigopalan** [mc2-center/mc2-center-dcc#65]
To help with tool and dataset uploads, add[ script](https://github.com/mc2-center/mc2-center-dcc/blob/main/utils/create_id_folders.py) that adds folder Synapse IDs for each manifest view.

**Comment by aclayton555** [comment]
24-6 close out: some additional updates pending. @aditigopalan will file tickets for these, then close this out
